#
# IMPORTANT: use ./compose-dev rather than calling `docker compose` directly.
#
# Docker Composition for:
# - Skewed Emacs
# - Gendl Development Environment
# - Node.js container for Lisply-Mcp and Claude Code.
#
# Usage:
#   ./compose-dev up                     # Start all services
#   ./compose-dev down                   # Stop all services
#

networks:
  skewed-network:
    name: ${DOCKER_NETWORK_NAME:-skewed-network}
    driver: bridge

services:

  skewed-emacs:
    image: gornskew/${EMACS_IMAGE_BASE:-skewed-emacs}:${EMACS_IMAGE_BRANCH:-master}
    container_name: ${EMACS_IMAGE_BASE:-skewed-emacs}
    hostname: ${EMACS_IMAGE_BASE:-skewed-emacs}
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "7081:7080"
    environment:
      - HTTP_PORT=7080
      - HTTP_HOST_PORT=7081
      - START_HTTP=true
      - START_SWANK=false
      - SWANK_PORT=4200
      - DISPLAY=${DISPLAY:-:0}
      - TERM=${TERM}
      - COLORTERM=${COLORTERM}
    volumes:
      - type: bind
        source: ${PROJECTS_DIR}
        target: /projects
        bind:
          create_host_path: true
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "${DOCKER_GROUP_ID:-999}"
    networks:
      - skewed-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/lisply/ping-lisp"]
      interval: 108s
      timeout: 3s
      retries: 3
      start_period: 10s

  gendl-ccl:
    image: genworks/${GENDL_IMAGE_BASE:-gendl}:${GENDL_IMAGE_BRANCH}-ccl
    container_name: ${GENDL_IMAGE_BASE:-gendl}-ccl
    hostname: gendl-ccl
    user: root
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "9081:9080"
      - "4201:4200"
    environment:
      - HTTP_PORT=9080
      - HTTP_HOST_PORT=9081
      - HTTPS_PORT=9443
      - HTTPS_HOST_PORT=9444
      - SWANK_PORT=4200
      - SWANK_HOST_PORT=4201
      - TELNET_PORT=4023
      - TELNET_HOST_PORT=4024
      - START_HTTP=true
      - START_HTTPS=false
      - START_SWANK=true
      - START_TELNET=false
      - GENDL_MODE=default
      - HOST_USER_UID=${HOST_USER_UID:-1000}
    volumes:
      - type: bind
        source: ${PROJECTS_DIR}
        target: /projects
        bind:
          create_host_path: true
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "${DOCKER_GROUP_ID:-999}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - skewed-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/lisply/ping-lisp"]
      interval: 72s
      timeout: 3s
      retries: 3
      start_period: 15s

  gendl-sbcl:
    image: genworks/${GENDL_IMAGE_BASE}:${GENDL_IMAGE_BRANCH}-sbcl
    container_name: ${GENDL_IMAGE_BASE}-sbcl
    hostname: ${GENDL_IMAGE_BASE}-sbcl
    user: root
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "9091:9090"
      - "4211:4210"
    environment:
      - HTTP_PORT=9090
      - HTTP_HOST_PORT=9091
      - HTTPS_PORT=9453
      - HTTPS_HOST_PORT=9454
      - SWANK_PORT=4210
      - SWANK_HOST_PORT=4211
      - TELNET_PORT=4033
      - TELNET_HOST_PORT=4034
      - START_HTTP=true
      - START_HTTPS=false
      - START_SWANK=true
      - START_TELNET=false
      - GENDL_MODE=default
      - HOST_USER_UID=${HOST_USER_UID:-1000}
    volumes:
      - type: bind
        source: ${PROJECTS_DIR}
        target: /projects
        bind:
          create_host_path: true
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "${DOCKER_GROUP_ID:-999}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - skewed-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/lisply/ping-lisp"]
      interval: 90s
      timeout: 3s
      retries: 3
      start_period: 15s


  lisply-mcp:
    image: gornskew/${NODE_IMAGE_BASE}:${NODE_IMAGE_BRANCH:-master}
    container_name: ${NODE_IMAGE_BASE_NAME:-lisply-mcp}
    hostname: ${NODE_IMAGE_BASE_NAME:-lisply-mcp}
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "3001:3000"
      - "8081:8080"
      - "9001:9000"
    volumes:
      - type: bind
        source: ${PROJECTS_DIR}
        target: /projects
        bind:
          create_host_path: true
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USER_CONFIG_DIR}:/home/node/.config
    environment:
      - HOST_EMACS_URL=http://host.docker.internal:7080
    group_add:
      - "${DOCKER_GROUP_ID:-999}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - skewed-network
    working_dir: /projects

# 
# volumes:
#   emacs-cache:
#   gendl-cache:
#   