#!/bin/bash
# Generate .env file for docker-compose
# Run this script to create your_processors local .env file

set -e

echo "Generating .env file for docker-compose..."

# Detect current user's home directory
if [ -z "$USER_HOME" ]; then
    USER_HOME="$HOME"
fi

# Define variables in the script's environment
HOST_USER_UID=$(id -u)
DOCKER_GROUP_ID=$(getent group docker | cut -d: -f3 || echo 999)
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD || echo "master")

# Detect host timezone (best-effort)
HOST_TZ=$(
  timedatectl show -p Timezone --value 2>/dev/null || \
  cat /etc/timezone 2>/dev/null || \
  echo "Etc/UTC"
)


# Create .env file
cat > .env << EOF
# Docker Compose Environment Variables
# Generated by ./generate-env.sh

# User paths
USER_HOME=$USER_HOME
PROJECTS_DIR=$USER_HOME/projects

# User/Group IDs
HOST_USER_UID=$HOST_USER_UID
DOCKER_GROUP_ID=$DOCKER_GROUP_ID

# Image and Container names
CURRENT_BRANCH=$CURRENT_BRANCH
EMACS_IMAGE_BRANCH=$CURRENT_BRANCH
EMACS_IMAGE_BASE=skewed-emacs
GENDL_IMAGE_BRANCH=$CURRENT_BRANCH
GENDL_IMAGE_BASE=gendl

# Network name
DOCKER_NETWORK_NAME=skewed-network
TERM=xterm-256color
COLORTERM=truecolor

$(if [ -f "$USER_HOME/.emacs-local" ]; then
    echo "EMACS_LOCAL_SRC=$USER_HOME"
    echo "# Found ~/.emacs-local → will be mounted read-only into container"
fi)

# Timezone (detected from host)
TZ=$HOST_TZ

EOF

echo ""
echo ".env file has the following settings:"
echo "CURRENT_BRANCH: $CURRENT_BRANCH"
echo "PROJECTS: $USER_HOME/projects"
echo "HOST_USER_UID: $HOST_USER_UID"  # Fixed typo: HOST_USER_ID to HOST_USER_UID
echo ""

# Handle .emacs-local volume mount conditionally (for deployments without .emacs-local)
if [ ! -f "$USER_HOME/.emacs-local" ]; then
    cat > zz-runtime-override.yml << 'OVERRIDE_EOF'
# Runtime override - exclude .emacs-local volume when file doesn't exist
# Generated by generate-env.sh - DO NOT EDIT
# The zz- prefix ensures this merges last in compose-dev's lexicographic ordering
version: '3.8'
services:
  skewed-emacs:
    volumes:
      - ${PROJECTS_DIR}:/projects
      - ${USER_HOME}/.gemini/google_accounts.json:/home/emacs-user/.gemini/google_accounts.json
      - ${USER_HOME}/.gemini/oauth_creds.json:/home/emacs-user/.gemini/oauth_creds.json
      - ${USER_HOME}/.codex/auth.json:/home/emacs-user/.codex/auth.json
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # .emacs-local volume OMITTED - file doesn't exist on host
OVERRIDE_EOF
    echo "Created zz-runtime-override.yml (no .emacs-local file detected)"
else
    # Remove override if .emacs-local now exists
    if [ -f "zz-runtime-override.yml" ]; then
        rm -f zz-runtime-override.yml
        echo "Removed zz-runtime-override.yml (.emacs-local file now exists)"
    fi
fi
