#!/bin/bash
#
# setup-ssh.sh - Generate SSH keys for skewed-emacs <-> lisply-mcp communication
#
# This script should be run ONCE on the host (or from inside skewed-emacs container)
# to set up passwordless SSH access from skewed-emacs to lisply-mcp.
#
# The keys are stored in /projects/skewed-emacs/ssh-keys/ which is mounted into
# both containers.
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SSH_KEYS_DIR="$SCRIPT_DIR/ssh-keys"
PRIVATE_KEY="$SSH_KEYS_DIR/id_ed25519"
PUBLIC_KEY="$SSH_KEYS_DIR/id_ed25519.pub"
AUTHORIZED_KEYS="$SSH_KEYS_DIR/authorized_keys"
SSH_CONFIG="$SSH_KEYS_DIR/config"

echo "=== Setting up SSH keys for skewed-emacs <-> lisply-mcp ==="
echo ""

# Create ssh-keys directory if it doesn't exist
mkdir -p "$SSH_KEYS_DIR"
chmod 700 "$SSH_KEYS_DIR"

# Generate key pair if it doesn't exist
if [ -f "$PRIVATE_KEY" ]; then
    echo "SSH key already exists at $PRIVATE_KEY"
    echo "To regenerate, delete $SSH_KEYS_DIR and run this script again."
else
    echo "Generating new ed25519 SSH key pair..."
    ssh-keygen -t ed25519 -f "$PRIVATE_KEY" -N "" -C "skewed-emacs-to-lisply-mcp"
    echo "Key pair generated."
fi

# Create authorized_keys from public key
echo "Creating authorized_keys file..."
cp "$PUBLIC_KEY" "$AUTHORIZED_KEYS"
chmod 644 "$AUTHORIZED_KEYS"

# Create SSH config for easy connection
echo "Creating SSH config..."
cat > "$SSH_CONFIG" << 'EOF'
# SSH config for skewed-emacs -> lisply-mcp connection
# This file is auto-generated by setup-ssh.sh

Host lisply-mcp
    HostName lisply-mcp
    User node
    IdentityFile ~/.ssh/id_ed25519
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR
EOF
chmod 644 "$SSH_CONFIG"

# Set proper permissions on private key
chmod 600 "$PRIVATE_KEY"

echo ""
echo "=== SSH Setup Complete ==="
echo ""
echo "Files created in $SSH_KEYS_DIR/:"
ls -la "$SSH_KEYS_DIR/"
echo ""
echo "These files will be mounted into the containers by docker-compose.yml:"
echo "  - skewed-emacs: $SSH_KEYS_DIR -> /home/emacs-user/.ssh (read-only)"
echo "  - lisply-mcp:   $AUTHORIZED_KEYS -> /home/node/.ssh/authorized_keys (read-only)"
echo ""
echo "Next steps:"
echo "  1. Ensure lisply-mcp is running SSH-enabled build (./compose-dev up)"
echo "  2. From skewed-emacs terminal, test: ssh lisply-mcp echo 'success'"
echo "  3. Use claudly, geminly, codexly commands"
echo ""
