#!/bin/zsh

ZSH_DISABLE_COMPFIX=true

. $HOME/.bash_profile

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/dcooper8/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
